version: '3'
services:
  shop:
    image: shop:1.0
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    command: java -jar shop.jar
    restart: always

    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
